#!/bin/bash

export CONTAINER_ENGINE=podman

export BOOTSTRAP_SERVERS=kafka:19092
export SCHEMA_REGISTRY_URL=http://schema-registry:8081
export CONNECTORS_URL=http://connect:8083
export ELASTIC_URL=http://elasticsearch:9200
export KSQLDB_INTERNAL_ENDPOINT=http://ksqldb-server:8088

export KAFKA_EXTERNAL_SERVERS=localhost:9092
export SCHEMA_REGISTRY_EXTERNAL_URL=http://localhost:8081
export CONNECTORS_EXTERNAL_URL=http://localhost:8083
export ELASTIC_EXTERNAL_URL=http://localhost:9200
export KSQLDB_EXTERNAL_ENDPOINT=http://localhost:8088

export REPLICATION_FACTOR=1

echo BOOTSTRAP_SERVERS $BOOTSTRAP_SERVERS
echo SCHEMA_REGISTRY_URL $SCHEMA_REGISTRY_URL
echo ELASTIC_URL $ELASTIC_URL
echo KSQLDB_INTERNAL_ENDPOINT $KSQLDB_INTERNAL_ENDPOINT
echo
echo KAFKA_EXTERNAL_SERVERS $KAFKA_EXTERNAL_SERVERS
echo SCHEMA_REGISTRY_EXTERNAL_URL $SCHEMA_REGISTRY_EXTERNAL_URL
echo CONNECTORS_EXTERNAL_URL $CONNECTORS_EXTERNAL_URL
echo KSQLDB_EXTERNAL_ENDPOINT $KSQLDB_EXTERNAL_ENDPOINT
echo ELASTIC_EXTERNAL_URL $ELASTIC_EXTERNAL_URL
echo
echo REPLICATION_FACTOR $REPLICATION_FACTOR

